export const QUEST_DEFINITIONS = {

  // ── TUTORIAL (one-time) ──────────────────────────────────────
  tutorial_build_warehouse: {
    type: 'tutorial',
    title: 'Построй склад',
    description: 'Улучши Склад до уровня 2',
    icon: '📦',
    condition: { building: 'warehouse', level: 2 },
    reward: { wood: 500, stone: 300 },
    xp: 50,
    order: 1,
  },
  tutorial_build_barracks: {
    type: 'tutorial',
    title: 'Построй казарму',
    description: 'Улучши Казарму до уровня 1',
    icon: '⚔️',
    condition: { building: 'barracks', level: 1 },
    reward: { iron: 200, silver: 50 },
    xp: 50,
    order: 2,
  },
  tutorial_train_troops: {
    type: 'tutorial',
    title: 'Первая армия',
    description: 'Обучи 20 воинов любого типа',
    icon: '🗡️',
    condition: { total_units: 20 },
    reward: { food: 400, silver: 100 },
    xp: 75,
    order: 3,
  },
  tutorial_send_scout: {
    type: 'tutorial',
    title: 'Первая разведка',
    description: 'Отправь разведчиков к любому поселению',
    icon: '🔍',
    condition: { scouts_sent: 1 },
    reward: { silver: 200 },
    xp: 75,
    order: 4,
  },
  tutorial_join_alliance: {
    type: 'tutorial',
    title: 'Найди союзников',
    description: 'Вступи в альянс или создай свой',
    icon: '🛡',
    condition: { in_alliance: true },
    reward: { wood: 1000, stone: 1000, iron: 500 },
    xp: 100,
    order: 5,
  },
  tutorial_first_attack: {
    type: 'tutorial',
    title: 'Первая битва',
    description: 'Атакуй лагерь разбойников или поселение',
    icon: '⚔️',
    condition: { attacks_sent: 1 },
    reward: { silver: 500, iron: 300 },
    xp: 150,
    order: 6,
  },
  tutorial_research: {
    type: 'tutorial',
    title: 'Путь учёного',
    description: 'Исследуй первую технологию',
    icon: '📜',
    condition: { researches_completed: 1 },
    reward: { silver: 300 },
    xp: 100,
    order: 7,
  },

  // ── DAILY (reset every 24h) ───────────────────────────────────
  daily_collect_resources: {
    type: 'daily',
    title: 'Сбор ресурсов',
    description: 'Собери 5000 ресурсов суммарно',
    icon: '🪵',
    condition: { resources_collected: 5000 },
    reward: { silver: 200 },
    xp: 30,
  },
  daily_train_troops: {
    type: 'daily',
    title: 'Пополнить ряды',
    description: 'Обучи 50 воинов за день',
    icon: '⚔️',
    condition: { units_trained: 50 },
    reward: { iron: 300, food: 200 },
    xp: 40,
  },
  daily_upgrade_building: {
    type: 'daily',
    title: 'Строитель',
    description: 'Улучши любое здание',
    icon: '🏛',
    condition: { buildings_upgraded: 1 },
    reward: { wood: 500, stone: 500 },
    xp: 35,
  },
  daily_send_attack: {
    type: 'daily',
    title: 'Воин дня',
    description: 'Отправь армию в атаку',
    icon: '🗡️',
    condition: { attacks_sent: 1 },
    reward: { silver: 150, iron: 200 },
    xp: 50,
  },
  daily_market_trade: {
    type: 'daily',
    title: 'Торговец',
    description: 'Совершить сделку на рынке',
    icon: '💰',
    condition: { trades_completed: 1 },
    reward: { silver: 300 },
    xp: 40,
  },

  // ── LONG-TERM ─────────────────────────────────────────────────
  long_second_settlement: {
    type: 'long_term',
    title: 'Расширение владений',
    description: 'Захвати или основай второе поселение',
    icon: '🏰',
    condition: { settlements_count: 2 },
    reward: { wood: 5000, stone: 5000, iron: 2000, silver: 1000 },
    xp: 500,
  },
  long_win_10_battles: {
    type: 'long_term',
    title: 'Ветеран',
    description: 'Победи в 10 боях',
    icon: '⚔️',
    condition: { victories: 10 },
    reward: { silver: 2000, iron: 1000 },
    xp: 400,
  },
  long_unlock_20_techs: {
    type: 'long_term',
    title: 'Учёный',
    description: 'Разблокируй 20 уровней технологий',
    icon: '📜',
    condition: { research_levels: 20 },
    reward: { silver: 3000 },
    xp: 600,
  },
  long_alliance_member: {
    type: 'long_term',
    title: 'Братство',
    description: 'Состоять в альянсе 7 дней',
    icon: '🛡',
    condition: { alliance_days: 7 },
    reward: { wood: 3000, stone: 3000, iron: 1500 },
    xp: 300,
  },
};

export type QuestType = keyof typeof QUEST_DEFINITIONS;
